### ISSUE TITLE
Add more tiles

### ISSUE THREAD

**Issue by Hugman76** [DawnTeamMC/Artisanat#20]
The design for tiles is based on dark prismarine
- [ ] Andesite Tiles
- [ ] Diorite Tiles
- [ ] Granite Tiles
- [ ] Sandstone Tiles
- [ ] Cobblestone Tiles
- [ ] Mossy Cobblestone Tiles
- [ ] Tile variants for #16
- [x] Brick Tiles
- [ ] Terracotta Tiles
- [ ] Tile variants for #17 
- [ ] Prismarine Tiles
- [ ] Prismarine Brick Tiles
- [ ] Nether Tiles (based on nether bricks)
- [ ] Red Nether Tiles
- [ ] Tile variants for #18 
- [ ] Blackstone Tiles
- [ ] Quartz Tiles
- [ ] End Stone Tiles
- [ ] End Stone Brick Tiles
- [ ] Purpur Tiles
